version: "3.8"

services:
  seeable-db:
    image: postgres:latest
    volumes:
      - seeable-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    restart: always 
    ports:
      - 54321:5432
    networks:
        - seeable-network

  seeable-dw:
    image: postgres:latest
    volumes:
      - seeable-data-warehouse:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATA_WAREHOUSE_DB}
      POSTGRES_PASSWORD: ${DATA_WAREHOUSE_PASSWORD}
      POSTGRES_USER: ${DATA_WAREHOUSE_USER}
    restart: always
    ports:
      - 54322:5432
    networks:
      - seeable-network
      - seeable-airbyte-network

volumes:
  seeable-data:
  seeable-data-warehouse:

networks:
  seeable-network:
  seeable-airbyte-network:
    name: airbyte_airbyte_public
    external: true
