version: "3.8"

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: seeable
      POSTGRES_PASSWORD: seeable
      POSTGRES_USER: seeable
    ports:
      - 54321:5432
    restart: on-failure:3

volumes:
  postgres-data:
