version: "3.8"

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: seeable
      POSTGRES_PASSWORD: seeable
      POSTGRES_USER: seeable
    ports:
      - 54321:5432
    restart: on-failure:3
  seeable-server:
    image: seeable-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SEEABLE_ENV: local
      DATABASE_URL_READER: postgres://seeable:seeable@postgres:5432/seeable
      DATABASE_URL_WRITER: postgres://seeable:seeable@postgres:5432/seeable
      COOKIE_SECRET: cookie-secret-secret-secret-secret-secret-secret-secret
    ports:
      - 3042:3000
    restart: always

volumes:
  postgres-data:
